### ISSUE TITLE
compile fix...

### ISSUE THREAD

**Issue by PostImpatica** [MSOpenTech/cordova-plugin-auth-dialog#5]
I had to remove about 4 lines in the authdialog-strings.xml file that contained:
 product="nosdcard"

this was the only way i could get it to compile for the android because it kept giving me duplicate string error during "cordova build android" phase.  I could have probably troubleshot this but after removing the lines it compiled and it's running great so i guess i don't care.

**Comment by sgrebnov** [comment]
Confirm this issue, thx @helzgate for letting us know
