### ISSUE TITLE
auth dialog on android

### ISSUE THREAD

**Issue by amitkumar3968** [MSOpenTech/cordova-plugin-auth-dialog#8]
Hi ,
 on iOS, it is working fine, but not able to run on android.
Though , the PR is merged for android.
Can you please update README for android  for hitting the authdialog.

Thanks

**Comment by amitkumar3968** [comment]
Hi, 
got the auth dialog, just by opening inappbrowser in android.
now, working on getting the success callback, as, i have to close the browser and open other window.
Thanks.

**Comment by pallaviMN** [comment]
@amitkumar3968 , can you please tell me how to call this plugin for android & iOS.

**Comment by pallaviMN** [comment]
i am not getting auth dialog at all

**Comment by amitkumar3968** [comment]
@pallaviMN  - sorry for the delay, i just read the github mail.
You just have to add this plugin in your cordova project and then call the  cordova.InAppBrowser.open function with your url having authentication challenge.

Hope , this may clear your doubts.
Thanks
